### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by kaiforth** [webleon/Hackintosh-OptiPlex-7080-MT#1]
第一遍读条之后正常会多出现一个启动的选项，可是我的电脑没出现。

**Comment by webleon** [comment]
你的配置是什么？
是否已经解锁Cfg_lock，并把DVMT设置为64M？

**Comment by kaiforth** [comment]
cpu是 i7 10700
显卡  核显
Dell微型计算机  产品型号 OptiPlex 7080 Tower
其他BIOS是和你设置的一样的
我用Grub 那个软件设置了这俩个
setup_var 0xF5 0x02
setup_var 0x3E 0x00


镜像用的是这个 https://blog.daliansky.net/macOS-Monterey-12.0.1-21A559-Release-version-with-OC-0.7.5-CLOVER-5141-and-PE-original-image.html

每次我点击 install macOS Monterey那个图标之后  出现苹果的logo  然后读进度条到四分之一左右就卡住了，前几次是卡住自动重启了，然后我再进入oc那个界面还是就那几个选项，等我再点击 install macOS Monterey那个图标他说我之前安装时错误退出了按任意键继续，然后又是出现苹果logo，重新开始读条，无限重复

**Comment by webleon** [comment]
如果没有独立显卡，需要把 platformID 改为07009B3E 或者 00009B3E，并在boot-args中去掉 agdpmod=pikera 参数。

**Comment by kaiforth** [comment]
今天试了一下把 platformID 改为07009B3E 或者 00009B3E都不行，boot-args这个参数直接留空白就行吧。还是一样的效果

**Comment by kaiforth** [comment]
![95ED928450D0C56A0FC54CAA1012975C](https://user-images.githubusercontent.com/49133630/144541326-eb10ba2b-0716-4aa4-97ea-47db401749d8.jpg)
我加了-v属性 出现了这个错误

**Comment by kaiforth** [comment]
![16D3489AF4FB76ACC3DE83F5B8C57053](https://user-images.githubusercontent.com/49133630/144548376-721848a9-35c1-47da-8b92-30e3f7995e8d.jpg)

**Comment by kaiforth** [comment]
我用镜像中自带的oc引导成功了，可是安装之后很卡，而且没有声音

**Comment by webleon** [comment]
截图中没有太多有用的信息，大概率还是显卡的问题，你可以在BIOS中禁用PCIe插槽，并且使用这个完整的核显缓冲帧补丁
[config_UHD630.plist.zip](https://github.com/webleon/Hackintosh-OptiPlex-7080-MT/files/7647212/config_UHD630.plist.zip)

**Comment by liuyuejinqiu** [comment]
@kaiforth 同学你好，请问问题解决了吗，我这边和你相同的配置相同的显示器，同样的问题

**Comment by kaiforth** [comment]
> @kaiforth 同学你好，请问问题解决了吗，我这边和你相同的配置相同的显示器，同样的问题

是不是回复错人了，我那个调了调驱动就好了

**Comment by liuyuejinqiu** [comment]
@kaiforth 没有回复错，我如果没看错，咱们离的不远，我现场找你烤一下efi方便吗，或者辛苦你把调整的参数发一下，非常感谢

**Comment by kaiforth** [comment]
> @kaiforth 没有回复错，我如果没看错，咱们离的不远，我现场找你烤一下efi方便吗，或者辛苦你把调整的参数发一下，非常感谢
额，我那个已经找不到了，好久之前了，现在不用黑苹果了。。。。

**Comment by liuyuejinqiu** [comment]
> > @kaiforth 没有回复错，我如果没看错，咱们离的不远，我现场找你烤一下efi方便吗，或者辛苦你把调整的参数发一下，非常感谢
> > 额，我那个已经找不到了，好久之前了，现在不用黑苹果了。。。。

好的，感谢，祝小伙伴开工大吉
