### ISSUE TITLE
集成显卡无法使用DP转hdmi显示器

### ISSUE THREAD

**Issue by qq987462183** [webleon/Hackintosh-OptiPlex-7080-MT#11]
7080MT i7版本
DP显示器直接连接主板DP接口可以正常显示，但是DP转hdmi线连接的显示器黑屏并且无法识别到，请问能解决吗

**Comment by webleon** [comment]
尝试换线

**Comment by wangliTeam** [comment]
你好,尝试了三条DP转HDMI线,得到一样的结果:插上去之后,屏幕没有任何反应,同时正常显示的DP屏幕会变卡顿,一段时间后恢复正.

**Comment by wangliTeam** [comment]
> 尝试换线
你好,更新了13.0,尝试了三条DP转HDMI线,得到一样的结果:插上去之后,屏幕没有任何反应,同时正常显示的DP屏幕会变卡顿,一段时间后恢复正常不卡顿了,显示器还是没有丝毫反应
