### ISSUE TITLE
install mac os 进度条三分之一时重启，怎么解

### ISSUE THREAD

**Issue by liuyuejinqiu** [webleon/Hackintosh-OptiPlex-7080-MT#15]

**Comment by webleon** [comment]
信息太少，无法判断。先排除UEFI设置和DVMT/CFG_lock编辑问题。

**Comment by liuyuejinqiu** [comment]
boot config 加上 -v 后,最后输出 couldn't alloc class “applekeystoreTest”
RadeonSensor initislizedRadeonSensor freeing upApple16X50UARTSync2: Detected 16550RF/C/CF FIFO=16 MaxBaud=115200
GTrace synchronization point 1
然后就重启了

**Comment by webleon** [comment]
我不知道你的配置，也不知道你的设置。
如果UEFI设置好了，DVMT/CFG_lock也编辑好了，且你使用的是核显，可以在Device Properties 换一个 PciRoot(0x0)/Pci(0x2,0x0) 的配置，config里有，我注释掉的那条。

**Comment by liuyuejinqiu** [comment]
好的，感谢，配置就是DELL 7080MT原装配置，我也没设置啥，下载了一个13.1的带引导的镜像，直接把您的efi copy 过去替换了，使用核显，我是小白一个。我再学学，再次感谢。

**Comment by webleon** [comment]
仔细看readme

**Comment by liuyuejinqiu** [comment]
运行ru.efi尝试修改编辑 DVMT/CFG_lock 结果无法找到EFI Variable Name 中的 CpuSetup和SaSetup,请问大佬这块还有啥办法处理
![img_v2_e52523ad-a9cb-45ec-83c7-5291fa1e664l_MIDDLE](https://user-images.githubusercontent.com/11872015/212817520-15b2e968-a9b0-4298-959d-fadb38fcf56b.jpg)

**Comment by liuyuejinqiu** [comment]
问题同一，https://github.com/webleon/Hackintosh-OptiPlex-7080-MT/issues/1,暂时无解
