### ISSUE TITLE
Can i use modGRUBShell

### ISSUE THREAD

**Issue by alomar-mac** [webleon/Hackintosh-OptiPlex-7080-MT#2]
Hi
can I use can use modGRUBShell (Modified GRUB Shell) to  Disable CFG lock (unlock)
I find it difficult to use ru-uefi

Thank you

**Comment by webleon** [comment]
seems setup_var is not available for the 7080 UEFI, but you can still give it a try.

**Comment by alomar-mac** [comment]
Do you have complete command to try 🌺

setup_var .......

**Comment by alomar-mac** [comment]
I do it with RU.efi

I am follow this guide

https://homanhuang.medium.com/how-to-hack-pc-bios-cfg-unlock-412d7128d0e3

Thank You
