### ISSUE TITLE
关机异常，每次开机的时候提示"you show down your computer because of a problem"

### ISSUE THREAD

**Issue by cai-hd** [webleon/Hackintosh-OptiPlex-7080-MT#4]
首先感谢老哥提供的EFI，所有的功能都可以使用，唯独关键的时候时有些异常，具体表现为：
1. 点了关机按钮后，系统会卡住
2. 然后大约3-4秒断电，没有debug日志输出
3. 在开机的时候就是会出现这个
4. 休眠在启动的时候也有这个提示 

<img width="535" alt="WX20220220-104842@2x" src="https://user-images.githubusercontent.com/44453960/154826403-5ff721ae-46e2-42f0-a98c-fe269e55bb07.png">

另外我的机型和你有点区别，我是7080SFF，比你这个小一号的主机，貌似是Q490的主板 

配置：
* CPU i7-10700F
* 硬盘  WD SN750 500G
* 内存  16 *2 3200 英睿达
* 显卡  AMD RX640 
* 显示器 Dell 3219

**Comment by webleon** [comment]
硬件不同，无法判断具体原因。
可以试试看OC文档类似问题的解决方案：https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html
