### ISSUE TITLE
bcm943602cs wifi 可用，蓝牙无法打开

### ISSUE THREAD

**Issue by xiecang** [webleon/Hackintosh-OptiPlex-7080-MT#5]
感谢老哥提供的 efi，我使用后一切都正常，目前只发现蓝牙不可用（显示图标，但是无法打开）（wifi 使用正常）
我的机器是 7080SFF，比你这个小一号的主机

cpu: 10400 i5
网卡: bcm943602cs
![image](https://user-images.githubusercontent.com/16369161/155258283-1a38ff04-49ce-4730-a9f7-8a1a85195c86.png)

在 Windows下安装驱动，蓝牙可用
系统是Monterey 12.1

没有解决思路，请求指教

**Comment by webleon** [comment]
蓝牙控制器会用到USB端口，由于主板不一样，USB端口定义可能不一样，需要重新定制usbports。

**Comment by xiecang** [comment]
> 蓝牙控制器会用到 USB 端口，由于主板不一样，USB 端口定义可能不一样，需要重新定制 usbports。

我比较小白，请问定制 usbports 的话，只修改 USBMap.kext 为同机型的，其它配置保持不变可以吗？

还是需要其它修改，请问有资料推荐吗？

**Comment by webleon** [comment]
只替换文件应该是可以的。

**Comment by xiecang** [comment]
感谢老哥回复，我搜索了下定制方法，最终使用 USBToolBox + Hackintool 定制成功了，蓝牙可以正常使用了

我把定制的 usbports 放到了[这里](https://github.com/xiecang/Hackintosh-OptiPlex-7080-SFF/commit/e25bd808ee9f53368c96318b5435504c5726976e)
