### ISSUE TITLE
大佬，我的显卡貌似没有驱动起来

### ISSUE THREAD

**Issue by MessageDream** [webleon/Hackintosh-OptiPlex-7080-MT#7]
如题，有解决办法吗？
![截屏2022-06-23 19 35 10](https://user-images.githubusercontent.com/4122730/175290510-a38884e4-042f-4c75-bb8b-21e89a29e761.png)

**Comment by webleon** [comment]
什么显卡？

**Comment by MessageDream** [comment]
我想用内置的集成显卡，插上面的两个原机的dp口的话是启动时绿屏重启，我不确定是不是it给我加了独立显卡，但是下面有一个dp和一个hdmi口，插这个的dp口的话，能启动，但是显示图形卡显示器8m

**Comment by webleon** [comment]
DeviceProperties里面把带#的PciRoot(0x0)/Pci(0x2,0x0)项目#取消，把没有#的加上#

**Comment by MessageDream** [comment]
感谢大佬，记得里面还有个选项是两个#的，这一项不需要管吗？

**Comment by webleon** [comment]
看PCIe位置，只替换PciRoot(0x0)/Pci(0x2,0x0)的就可以。

**Comment by MessageDream** [comment]
好的好的，谢谢您
