### ISSUE TITLE
7080MT i9-10900型号无法进入安装界面

### ISSUE THREAD

**Issue by guodf** [webleon/Hackintosh-OptiPlex-7080-MT#8]
进入oc界面后，选择安装，滚动条进行一半就会自动重启

**Comment by webleon** [comment]
提供下log或者报错信息

**Comment by guodf** [comment]
配置如下（没有独立显卡）：
![SharedScreenshot](https://user-images.githubusercontent.com/7540349/181206554-9437b547-3fad-49c1-bb9d-748dd14f825e.jpg)

清空config.plist中的boot-args参数

无法看到日志信息，就是一个苹果logo，走到1/4时就重启了，无限循环。
与 [https://github.com/webleon/Hackintosh-OptiPlex-7080-MT/issues/1](https://github.com/webleon/Hackintosh-OptiPlex-7080-MT/issues/1)中的问题描述现象一致。

**Comment by webleon** [comment]
哦，没有独显啊，你把DeviceProperties里面的PciRoot(0x0)/Pci(0x2,0x0)项目注释掉，同时启用下我已经注释掉的那项##PciRoot(0x0)/Pci(0x2,0x0)来替换。

**Comment by guodf** [comment]
试了，还是一样的问题，我切换到5月份的release也是不行。
这个版本怎么开启日志模式？cfglock已解锁

**Comment by webleon** [comment]
boot-args加 -v

**Comment by guodf** [comment]
这个我用3dudu的显卡那段配置替换后报的错
[panic-2022-07-29-145855.txt](https://github.com/webleon/Hackintosh-OptiPlex-7080-MT/files/9217182/panic-2022-07-29-145855.txt)

另外，我用3dudu的efi安装成功了

**Comment by QQ3789457** [comment]
我的就是7080MT哦，不过CPU是10700的，我有完美的EFI，我不知道怎么在这里发出来，需要可以加我QQ3789457

**Comment by frank071129** [comment]
我这是i9 10900，用的rx560D独显，安装成功了，SSDT-Shutdown.aml这个还是不能删除，否则关机有问题。另外，dvmt 64M不知道怎么开启，好像独显不开也没有事。cfglock开启了，目前运行基本正常。
