### ISSUE TITLE
BCM94360CD wifi蓝牙异常

### ISSUE THREAD

**Issue by qq987462183** [webleon/Hackintosh-OptiPlex-7080-MT#9]
7080MT i7版本
免驱网卡BCM94360CD购自黑果小兵淘宝店，12.4系统，wifi 能搜索连接但是没有网络，蓝牙无法开启，请问该怎么解决啊

**Comment by webleon** [comment]
BCM94360CD在新版本可能非免驱，尝试添加OC提供的蓝牙无线驱动。
